title: Automated Testing Framework
description: Web application for creating, administrating and running automated tests.
authors:
    - Waylan Limberg
    - Tom Christie
use_logo: true
logo: /logo_atf.png
theme:  jekyll-theme-cayman
