# Site settings
title: Automated Testing Framework
email: atf@gmail.com
description: "Automated Testing Framework is a web application for creating, administrating and running automated tests."


# Team names, titles and social links
people:
- name: Andreea Alistar
  pic: 1
  position: Product Owner + Front-end Developer + QA
  social:
    - title: facebook
      url: https://www.facebook.com/alistar.andreea
    - title: linkedin
      url: https://www.linkedin.com/in/andreea-alistar-305331101/
    - title: envelope
      url: mailto:andreealistar@gmail.com

- name: Andrei Crividenco
  pic: 2
  position: Back-end Developer + QA
  social:
    - title: facebook
      url: https://www.facebook.com/zdxf.adf
    - title: linkedin
      url: https://www.linkedin.com/in/andrei-crividenco-76538814b/
    - title: envelope
      url: mailto:acrividenco@gmail.com

- name: Dumitru Cirimpei
  pic: 3
  position: Back-end Developer + QA
  social:
    - title: facebook
      url: https://www.facebook.com/mitrumd
    - title: linkedin
      url: https://www.linkedin.com/in/dumitru-cirimpei/
    - title: envelope
      url: mailto:cirimpei.dumitru@gmail.com

- name: Eugen Drăguțeanu
  pic: 4
  position: Front-end Developer + QA
  social:
    - title: facebook
      url: https://www.facebook.com/eugen.draguteanu
    - title: linkedin
      url: https://www.linkedin.com/in/eugeniu-draguteanu-510798103/
    - title: envelope
      url: mailto:draguteanu.eugen@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
