title: Automated Testing Framework
logo: logo_atf.png
format: web
use_logo: true
description: Web application for creating, administrating and running automated tests.

# Setup
tagline:      landing page
theme:  jekyll-theme-cayman
