title: Automated Testing Framework. Tests as first-class citizen.
description: Web application for creating, administrating and running automated tests.
use_logo: true
logo: /logo_atf.png
theme:  jekyll-theme-cayman
