title: Automated Testing Framework
logo: logo_atf.png
description: Automated Testing Framework is a web application for creating, administrating and running automated tests.
theme: jekyll-theme-minimal
markdown: rdiscount
permalink: pretty
paginate: 3
