title: Automated Testing Framework
description: Web application for creating, administrating and running automated tests.
show_downloads: true

# social
author: "Lore Pirri"
image: /logo_atf.png

use_logo: true
logo: /logo_atf.png

theme:  jekyll-theme-cayman
